# Generated by Django 3.1.7 on 2021-05-23 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20210523_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='username',
            new_name='user',
        ),
    ]
